server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_site?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 1021
  jackson:
    date-format: yyyy-MM-dd
  main:
    allow-circular-references: true
  redis:
    host: 127.0.0.1
    port: 6379
#alicloud:
#  oss:
#    endpoint: oss-cn-nanjing.aliyuncs.com
#    bucket: yxsite1
#  access-key:
#  secret-key:
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yaxingguo.mysitespring.entity
  configuration:
    map-underscore-to-camel-case: true